name: Export KiCad Images

on:
  workflow_call: # This makes the workflow reusable

jobs:
  export-kicad-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull KiCad Docker image
      run: |
        echo "Pulling KiCad Docker image..."
        docker pull kicad/kicad:nightly-full

    - name: Set directory permissions
      run: |
        echo "Setting directory permissions to 777..."
        sudo chmod -R 777 .

    # Run KiCad Docker container to export files
    - name: Export schematic, PCB, and 3D model
      run: |
        echo "Exporting schematic, PCB, and 3D model..."
        docker run --rm -v "${{ github.workspace }}:/workspace" -w /workspace kicad/kicad:nightly-full bash -c "

          # Export schematic
          mkdir -p images
          kicad-cli sch export svg -o 'images/sch' kicad/*.kicad_sch
          sudo mv images/sch/*.svg images/sch.svg
          sudo rm -r images/sch
          
          exit
        "
      # Commit and push the changes
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull
        git add images/*
        git commit -m "Auto-exported schematic"
        git push

    # Notify the user about completion
    - name: Notify completion
      run: echo "3D model image exported successfully into the 'images' directory and changes pushed to the repository."
