name: Export KiCad Images

on:
  workflow_call: # This makes the workflow reusable

jobs:
  export-kicad-files:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Create GitHub App token
      id: create_token
      uses: tibdex/github-app-token@v2.1.0
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
        # installation_id: ${{ secrets.MY_APP_INSTALLATION_ID }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull KiCad Docker image
      run: docker pull kicad/kicad:nightly-full

    - name: Set directory permissions
      run: sudo chmod -R 777 .

    - name: Export schematic, PCB, and 3D model
      run: |
        # ... your export logic ...
        echo "Running kicad-cli commands ..."
        docker run --rm -v "${{ github.workspace }}:/workspace" kicad/kicad:nightly-full bash -c "echo testing"
      
    # Additional steps to export VRML, run Rayhunter, etc. 
    # (as in your original script)...

    - name: Commit and push changes to main
      run: |
        git config user.name "My KiCad Export App"
        # Use a placeholder for email that matches the GitHub App pattern:
        git config user.email "123456+MyKiCadApp[bot]@users.noreply.github.com"

        git add images/*
        git commit -m "Auto-exported schematic, PCB, and 3D model" || echo "No changes to commit."
        git push origin main
      env:
        GITHUB_TOKEN: ${{ steps.create_app_token.outputs.token }}
