name: test2

on:
  workflow_call:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}

          private_key: ${{ secrets.APP_PRIVATE_KEY }}
   

      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"
